# -*- coding: utf-8 -*-
"""Robo Jala(grupo 1) 100%

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18hK9alsPlsB0ToBqG0RgYYm1t70CZsbo
"""

class Part():
    # características do robô
    def __init__(self, nome: str, nivelAtaque=0, nivelDefesa=0, energiaConsumida=0):
        self.nome = nome
        self.nivelAtaque = nivelAtaque
        self.nivelDefesa = nivelDefesa
        self.energiaConsumida = energiaConsumida

    # função que contém e retorna um dicionário com os dados do robô
    def get_dicionario(self):
        # formata a string, substituindo os espaços em branco e convertendo pra letras minúsculas
        formatar_string = self.nome.replace(" ", "_").lower()
        return {
            "{}_nome".format(formatar_string): self.nome.upper(),
            "{}_status".format(formatar_string): self.status_defesa(),
            "{}_ataque".format(formatar_string): self.nivelAtaque,
            "{}_defesa".format(formatar_string): self.nivelDefesa,
            "{}_energia_consumida".format(formatar_string): self.energiaConsumida,
        }

    # função pra reduzir a defesa a cada ataque
    def reduzir_defesa(self, nivelAtaque):
        self.nivelDefesa = self.nivelDefesa - nivelAtaque
        if self.nivelDefesa <= 0:
            self.nivelDefesa = 0

    # função para verificar se o nível de defesa
    def status_defesa(self):
        return self.nivelDefesa <= 0


class Robot:
    # a classe Robot define as características básicas do robô, interagindo com a classe Part que contém as partes do robo
    def __init__(self, nome, codigo_cor, roboSelecionado):
        self.nome = nome
        self.codigo_cor = codigo_cor
        self.energia = 100
        self.roboSelecionado = roboSelecionado
        # chama a classe Part e seus objetos, representando as partes do robô
        self.parts = [
            Part("Cabeça", nivelAtaque=10, nivelDefesa=10, energiaConsumida=5),
            Part("Arma", nivelAtaque=20,
                 nivelDefesa=0, energiaConsumida=10),
            Part("Braço esquerdo", nivelAtaque=10,
                 nivelDefesa=20, energiaConsumida=10),
            Part("Braço direito", nivelAtaque=10,
                 nivelDefesa=20, energiaConsumida=10),
            Part("Perna esquerda", nivelAtaque=8,
                 nivelDefesa=20, energiaConsumida=15),
            Part("Perna direita", nivelAtaque=12,
                 nivelDefesa=20, energiaConsumida=15),
        ]

    # imprime o status atual do robô
    def print_robo(self):
        print(self.codigo_cor)
        # representação visual do robô
        str_robot = personagens[self.roboSelecionado].format(**self.status_partes_robo())
        self.saudacao()
        self.print_energia()
        print(str_robot)
        print(cores["Preto"])

    def saudacao(self):
        print('=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=')
        print("Olá! Meu nome é ", self.nome)

    # porcentagem atual de energia
    def print_energia(self):
        print("Nós temos", self.energia, "% de energia sobrando")
        print('=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-==-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=')

    def status_partes_robo(self):
        # dicionário vazio
        part_status = {}
        # faz um loop adicionando as novas partes do robô ao dicionário
        for part in self.parts:
            status_dict = part.get_dicionario()
            part_status.update(status_dict)
        return part_status

    # verifica se o robô ainda tem partes com defesa disponível
    def parte_robo_disponivel(self):
        for part in self.parts:
            if part.status_defesa():
                return True
        return False

    # verifica se o robô está vivo ou morto com base na sua energia
    def robo_ligado(self):
        return self.energia >= 0

    # função de ataque de um robô contra outro
    def ataque(self, robo_inimigo, parte_atacante, parte_atacada):
        nivelAtaque = self.parts[parte_atacante].nivelAtaque
        nivelDefesa = robo_inimigo.parts[parte_atacada].nivelDefesa

        if nivelAtaque > nivelDefesa:
            dano = nivelAtaque - nivelDefesa
        else:
            dano = 0

        robo_inimigo.parts[parte_atacada].reduzir_defesa(nivelAtaque)

        # Aplica o dano diretamente na energia do robô inimigo
        self.energia -= self.parts[parte_atacada].energiaConsumida
        robo_inimigo.energia -= dano

        if self.energia < 0:
           self.energia = 0

        if self.energia < 0:
            self.energia = 0

cores = {
    "Preto": '\x1b[90m',
    "Azul": '\x1b[94m',
    "Ciano": '\x1b[96m',
    "Verde": '\x1b[92m',
    "Magenta": '\x1b[95m',
    "Vermelho": '\x1b[91m',
    "Branco": '\x1b[97m',
    "Amarelo": '\x1b[93m',
}

# função que permite ao usuário escolher nome e cor do robô
def criar_robo():
    print('====='*18)
    robot_nome = input("> Nome do robô: ")
    print('====='*18)
    roboSelecionado = selecionarPersonagem()
    codigo_cor = definir_cor()
    robot = Robot(robot_nome, codigo_cor, roboSelecionado)
    robot.print_robo()
    return robot


def definir_cor():
    print('---------'*12)
    cores_disponiveis = cores
    print("Cores disponíveis:")
    print('---------'*12)
    for key, value in cores_disponiveis.items():
        print(value, key)
    print(cores["Preto"])
    # .capitalize() permite que a entrada seja minúscula/maiúscula
    print('====='*21)
    cor_escolhida = input("> Escolha uma cor: ").capitalize()
    print('====='*21)
    # solução para cor inserida fora das opções e quebra de código.
    if cor_escolhida not in cores_disponiveis:
        print('=-=-='*18)
        print("Condição inválida! Insira uma cor que esteja disponível.")
        print('=-=-='*18)
        return definir_cor()
    else:
        return cores_disponiveis[cor_escolhida]

def selecionarPersonagem():
    print("Opções de personagem:")
    # Faz um loop pelos itens do dicionário personagens e exibe na tela cada opção disponível para o usuário selecionar
    for opcao, personagem in personagens.items():
        print(f"{opcao} - {personagem}")
        print('___________'*10)


    # Inicia um loop infinito, para que o usuário possa tentar selecionar um personagem até escolher uma opção válida
    while True:
        # tentativa de converter a entrada do usuário pra um número inteiro
        try:
            print('====='*21)
            opcaoSelecionada = int(input("Escolha o seu personagem=> "))
            print('====='*21)
            # Se a opção selecionada pelo usuário não estiver disponível no dicionário personagens, levanta um erro do tipo ValueError
            if opcaoSelecionada not in personagens.keys():
                raise ValueError
            # se a opção selecionada pelo usuário estiver disponível, retorna o número correspondente
            return opcaoSelecionada
        # se o usuário inserir uma opção inválida, exibe a mensagem de erro até o usuário inserir uma opção válida
        except ValueError:
            print('=-=-='*18)
            print("Opção inválida! Insira uma das opções disponíveis.")
            print('=-=-='*18)

# função que inicia o jogo
def play():
    playing = True
    print('=-=-='*18)
    print("-----------------Bem-vindo(a) ao jogo! Uma intensa batalha espera por você!---------------")
    print('=-=-='*18)
    print(" ")
    print('====='*18)
    print("---------------------Jogador 1, escolha com quem deseja batalhar-------------------------")
    robo_um = criar_robo()
    print('====='*18)
    print("---------------------Jogador 2, escolha com quem deseja batalhar-------------------------")
    robo_dois = criar_robo()
    robo_atual = robo_um
    robo_inimigo = robo_dois
    rodada = 0

    while playing:
        if rodada % 2 == 0:
            robo_atual = robo_um
            robo_inimigo = robo_dois
        else:
            robo_atual = robo_dois
            robo_inimigo = robo_um
        robo_atual.print_robo()
        print('====='*18)
        print("Qual parte devo usar para atacar?")
        parte_atacante = input("Escolha um número:")
        parte_atacante = int(parte_atacante)
        print('====='*18)
        robo_inimigo.print_robo()
        print('====='*18)
        print("Qual parte do inimigo devemos atacar?")
        parte_atacada = input("Escolha um número para atacar o inimigo: ")
        parte_atacada = int(parte_atacada)
        print('====='*18)
        robo_atual.ataque(robo_inimigo, parte_atacante, parte_atacada)
        rodada += 1
        if not robo_inimigo.robo_ligado() or robo_inimigo.parte_robo_disponivel() == False:
            playing = False
            print('====='*18)
            robo_atual.print_robo()
            print(f"Parabéns, {robo_atual.nome} ganhou!\n")

# ==================================== Opções de batalha ============================================
personagens = {
    1: r"""
        0: {cabeça_nome}
       Is available: {cabeça_status}
       Attack: {cabeça_ataque}                              
       Defense: {cabeça_defesa}
       Energy consumption: {cabeça_energia_consumida}
            ^
            |                  |1: {arma_nome}
            |                  |Is available: {arma_status}
      ___       ___            |Attack: {arma_ataque}
     [___] /~\ [___]           |Defense: {arma_defesa}
     |ooo|.\_/.|ooo|           |Energy consumption: {arma_energia_consumida}
     |888||   ||888|
  / /|888||   ||888|\ \
 /_./|###||___||###| \._\ ---> |2: {braço_esquerdo_nome}
 /~\  ~~~ /[_]\ ~~~   /~\      |Is available: {braço_esquerdo_status}
(O_O) /~~[_____]~~\  (O_O)     |Attack: {braço_esquerdo_ataque} 
     (  |       |  )            |Defense: {braço_esquerdo_defesa}
    [~` ]       [ '~]           |Energy consumption: {braço_esquerdo_energia_consumida}
    |~~|         |~~|           |
    |  |         |  |           |3: {braço_direito_nome}
   _<\/>_       _<\/>_          |Is available: {braço_direito_status}
  /_====_\     /_====_\         |Attack: {braço_direito_ataque}                                
                                |Defense: {braço_direito_defesa}          
             ^                   |Energy consumption: {braço_direito_energia_consumida}
             |
             |    
|4: {perna_esquerda_nome} 
|Is available: {perna_esquerda_status}
|Attack: {perna_esquerda_ataque}
|Defense: {perna_esquerda_defesa}
|Energy consumption: {perna_esquerda_energia_consumida}
|
|5: {perna_direita_nome}
|Is available: {perna_direita_status}
|Attack: {perna_direita_ataque}
|Defense: {perna_direita_defesa}
|Energy consumption: {perna_direita_energia_consumida}
 """,
  2: r"""
           0: {cabeça_nome}
           Is available: {cabeça_status}
           Attack: {cabeça_ataque}                              
           Defense: {cabeça_defesa}
           Energy consumption: {cabeça_energia_consumida}
                           ^
                           |                       |1: {arma_nome}
                          ___                      |Is available: {arma_status}
                         /[-])//  ___              |Attack: {arma_ataque}
                    __ --\ `_/~--|  / \            |Defense: {arma_defesa}
                  /_-/~~--~~ /~~~\\_\ /\           |Energy consumption: {arma_energia_consumida}
                  |  |___|===|_-- | \ \ \        
_/~~~~~~~~|~~\,   ---|---\___/----|  \/\-\             |2: {braço_esquerdo_nome}
~\________|__/   / // \__ |  ||  / | |   | |           |Is available: {braço_esquerdo_status}
         ,~-|~~~~~\--, | \|--|/~|||  |   | |           |Attack: {braço_esquerdo_ataque}
         [3-|____---~~ _--'==;/ _,   |   |_|           |Defense: {braço_esquerdo_defesa}
                     /   /\__|_/  \  \__/--/           |Energy consumption: {braço_esquerdo_energia_consumida}
                    /---/_\  -___/ |  /,--|    ------> |
                    /  /\/~--|   | |  \///             |3: {braço_direito_nome}
                   /  / |-__ \    |/                   |Is available: {braço_direito_status}
                  |--/ /      |-- | \                  |Attack: {braço_direito_ataque}
                 \^~~\\/\      \   \/- _               |Defense: {braço_direito_defesa}
                  \    |  \     |~~\~~| \              |Energy consumption: {braço_direito_energia_consumida}
                   \    \  \     \   \  | \      
                     \    \ |     \   \    \              |4: {perna_esquerda_nome} 
                       |~~|\/\|     \   \   |             |Is available: {perna_esquerda_status}
                     |   |/         \_--_- |\             |Attack: {perna_esquerda_ataque}
                     |  /            /   |/\/             |Defense: {perna_esquerda_defesa}
                      ~~             /  /                 |Energy consumption: {perna_esquerda_energia_consumida}
                                    |__/          ------> |
                                                          |5: {perna_direita_nome}
                                                          |Is available: {perna_direita_status}
                                                          |Attack: {perna_direita_ataque}
                                                          |Defense: {perna_direita_defesa}
                                                          |Energy consumption: {perna_direita_energia_consumida}
 """,
3: r"""
                        0: Cabelça                               
                        Is available: {cabeça_status}
                        Attack: {cabeça_ataque}                              
                        Defense: {cabeça_defesa}
                        Energy consumption: {cabeça_energia_consumida}
                                           ^
                                           |
                                           |
 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⠶⠟⠛⠛⠻⠶⠶⣶⣤⣤⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⡾⠋⣡⣴⣾⣿⣿⣿⣶⣶⣦⣤⣉⣉⠛⠛⠷⢶⣤⣄⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟⢉⣤⣾⣿⣿⣿⡿⠋⠁⠀⠀⠈⠉⠙⠛⠿⢷⣶⣤⣄⣉⠙⠛⠷⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⠟⢁⣴⣿⣿⣿⣿⠟⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⡟⠿⢶⣤⣄⠉⠻⣶⣄⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⠟⢁⣴⣿⣿⣿⣿⠟⠁⠀⠀⠀⠀⣀⣤⣤⣄⣀⠀⠀⠀⠀⠀⠀⠙⠓⠦⢄⣈⣻⣷⣄⠈⠻⣷⡀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⠟⢁⣴⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⣠⣾⣿⣛⠛⠛⠻⣿⣇⠀⠀⠀⠀⣤⣄⣀⠀⠈⠉⠛⠻⠃⠀⠈⠻⣦⡀⠀ ---------> |1: Veneno Acido
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟⢁⣴⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⢠⣾⡿⠋⠉⠛⠻⠶⣶⣿⣿⠀⠀⠀⠀⣿⣿⣿⣿⣶⣤⣀⠀⠀⠀⠀⠀⣸⡇⠀            |Is available: {arma_status}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡿⠁⣰⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⢀⣴⡿⠿⠿⢷⣶⣤⣀⣀⠀⢹⣿⡄⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⣠⡾⠟⠁⠀           |Attack: {arma_ataque}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡟⠀⣼⣿⣿⣿⠟⠁⠀⠀⠀⠀⢀⣴⣿⣿⣀⡀⠀⠀⠀⠉⠙⠛⠻⢿⣿⣇⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣇⣴⡟⠁⠀⠀⠀           |Defense: {arma_defesa}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡿⠀⣸⣿⣿⣿⠋⠀⠀⠀⠀⠀⢠⣾⡟⠉⠉⠛⠛⠿⢷⣶⣤⣄⣀⠀⠀⢸⣿⡄⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀⠀⠀           |Energy consumption: {arma_energia_consumida}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⣿⣿⣿⡇⠀⠀⠀⠀⠀⢠⣿⣯⣀⣀⡀⠀⠀⠀⠀⠀⠈⠉⠙⠛⢿⣿⡿⢁⣀⠀⠀⠹⣿⣿⠟⠋⣹⡿⠁⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣧⠀⢹⣿⣿⣇⠀⠀⠀⠀⠀⣿⡟⠉⠛⠛⠻⠿⠷⣶⣦⣤⣄⣀⣀⢀⣾⡟⣰⠟⠉⠳⣆⠀⠀⠀⣀⣾⠏⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⡄⠀⢻⣿⣿⡄⠀⠀⠀⠀⣿⣇⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠛⣿⡿⢰⡏⠀⠀⠀⠈⠛⠶⠾⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀------------> |2: Boca
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⡄⠀⢻⣿⣿⡀⠀⠀⠀⢹⣿⣦⣤⣤⣤⣤⣀⣀⣀⣀⣀⡀⢀⣿⡇⣼⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀             |Is available: {braço_esquerdo_status}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⣄⠀⢻⣿⣷⡀⠀⠀⠀⢿⣿⠉⠉⠉⠉⠙⠛⠛⠛⠛⠛⠻⣿⡇⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀              |Attack: {braço_esquerdo_ataque}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣆⠀⢻⣿⣷⡀⠀⠀⠈⣿⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⢿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀                |Defense: {braço_esquerdo_defesa}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣆⠀⢻⣿⣿⡄⠀⠀⠘⣿⣦⣤⣤⣤⣤⣤⣤⣤⣤⣴⣿⡇⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀              |Energy consumption: {braço_esquerdo_energia_consumida}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣦⠀⢻⣿⣿⡄⠀⠀⠘⣿⣏⠉⠉⠉⠉⠉⠀⠀⠀⢻⣿⠘⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣧⠀⠻⣿⣿⡄⠀⠀⠹⣿⡄⠀⠀⠀⠀⠀⠀⠀⢸⣿⡄⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣧⠀⠹⣿⣿⡄⠀⠀⠹⣿⣄⣤⣤⣤⣤⣤⣶⣾⣿⣧⢸⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀------------>|3: Escama
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣷⡀⠹⣿⣿⡄⠀⠀⢹⣿⡉⠉⠁⠀⠀⠀⠀⢸⣿⡌⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀              |Is available: {braço_direito_status}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢷⡀⠹⣿⣿⡄⠀⠀⢻⣷⡀⠀⠀⠀⠀⠀⠀⣿⣇⢹⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀              |Attack: {braço_direito_ataque}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢷⡄⠹⣿⣿⡄⠀⠀⢿⣷⣤⣤⣴⣶⠶⠿⠿⣿⡌⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀             |Defense: {braço_direito_defesa}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⡄⠹⣿⣿⡆⠀⠈⢿⣯⠀⠀⠀⠀⠀⠀⢿⣧⢹⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀              |Energy consumption: {braço_direito_energia_consumida}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⡄⠹⣿⣿⣄⠀⠘⣿⣧⠀⠀⢀⣀⣀⣼⣿⡄⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣆⠹⣿⣿⡄⠀⠘⣿⣿⠟⠛⠋⠉⠉⢻⣷⠸⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀------------>|4: Corpo
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣆⠹⣿⣿⡄⠀⠘⣿⣆⠀⠀⠀⠀⣸⣿⡇⢿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀              |Is available: {perna_esquerda_status}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣆⠹⣿⣿⡄⠀⠸⣿⣶⡶⠿⠛⠋⢻⣿⡘⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀             |Attack: {perna_esquerda_ataque}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣆⢹⣿⣿⡀⠀⠹⣿⡄⠀⠀⠀⣀⣿⣧⢹⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀              |Defense: {perna_esquerda_defesa}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⡆⢻⣿⣷⡀⠀⢹⣿⣶⠶⠟⠛⠻⣿⡄⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀              |Defense: {perna_esquerda_defesa}
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⡄⢻⣿⣧⠀⠀⢻⣿⠀⠀⠀⣀⣿⣧⢸⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡴⠒⠛⠛⠛⠒⠦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣷⠈⢿⣿⣇⠀⠈⢿⣷⡶⠟⠛⠻⣿⡄⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡴⠟⠁⢀⣀⠀⢶⣶⣶⣤⡈⠙⢦⣀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣇⠘⣿⣿⡆⠀⠘⣿⡆⠀⠀⣀⣿⣧⢸⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⣠⠾⠋⢀⣠⣾⡿⢿⣷⡄⠻⣿⣿⣿⣷⣄⡉⠳⣄⠀⠀⠀⠀⠀⠀⠀⣿⡀⢻⣿⣿⡀⠀⢻⣿⡾⠟⠋⢹⣿⡈⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣠⠞⠁⢀⣴⣿⠟⠉⠀⠀⠙⣿⣦⡈⠻⣿⣿⣿⣿⣦⡈⠻⣦⡀⠀⠀⠀⠀⢹⡇⠸⣿⣿⣇⠀⠘⣿⣆⣀⣤⣼⣿⡇⠻⢤⣀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣠⠞⠁⢀⣴⡿⠋⠁⠀⠀⠀⢀⣴⠟⠻⣿⣦⡈⠻⣿⣿⣿⣿⣷⣄⠙⢦⡀⠀⠀⢸⣷⠀⣿⣿⣿⠀⠀⣿⣿⠋⠉⠀⣿⡇⢠⣄⡉⠛⢶⣄⠀⠀⠀⠀⠀
⠀⠀⠀⢰⠋⠀⠀⠿⣿⣦⣄⡀⠀⢀⣴⡿⠁⠀⠀⢈⣿⢿⣶⣄⡙⠻⢿⣿⣿⣷⣦⡙⢷⣤⣸⣿⠀⣿⣿⣿⡇⠀⣿⣿⣤⣶⢾⣿⡇⢸⣿⣿⣷⣤⡈⠻⢦⡀⠀⠀    ---------> |5: Calda
⠀⠀⠀⠘⣧⠀⠀⠀⠈⠙⠻⢿⣷⣿⣏⡀⠀⠀⣠⡿⠃⠀⠉⢻⣿⣷⣦⣬⣙⣛⠻⠿⠶⠈⠻⠏⢠⣿⣿⣿⡇⠀⣿⡟⠉⠀⣸⣿⠃⢸⣿⣿⣿⡿⠟⢀⡀⠹⣦⠀               |Is available: {perna_direita_status}
⠀⠀⣀⡴⠋⠀⣠⣤⣄⠀⠀⠀⠈⠉⠛⠿⣷⣶⣿⣀⡀⠀⢠⡿⠁⠀⠉⣹⡿⠛⠿⠿⣿⣿⠂⠀⣼⣿⣿⣿⠁⢠⣿⣷⡾⢿⣿⠏⠀⠉⠉⠉⢁⣀⣴⣿⣿⣆⠘⣧               |Attack: {perna_direita_ataque}
⣠⠞⠋⠀⠴⣾⣿⣿⣿⣿⣦⣄⡀⠀⠀⠀⠀⠈⠙⠛⠿⢿⣿⣷⣤⣤⣤⣿⣥⣤⣴⣿⠟⠁⢀⣼⣿⣿⣿⠏⢀⣾⡟⢁⣴⣿⠏⢀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⣿              |Defense: {perna_direita_defesa}
⠻⠦⣤⣀⡀⠀⠈⠉⠛⠻⠿⢿⣿⣷⣶⣤⣀⠘⠻⠶⣦⣤⣀⣉⠉⠙⠛⠛⠛⠉⠉⠀⣀⣴⣿⣿⣿⡿⠋⣠⣾⣿⣷⡿⠟⠁⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⠟⠃⣰⠏              |Energy consumption: {perna_direita_energia_consumida}
⠀⠀⠀⠈⠉⠛⠓⠶⠦⣤⣄⣀⣀⡈⠉⠉⠛⠛⠷⠦⠀⠈⠉⠛⠛⠿⠿⠷⣾⣿⣿⣿⡿⠿⠿⠛⠁⠀⠀⠙⠛⠋⠁⠀⠀⠺⠿⠿⠿⠿⠟⠛⠛⣉⣁⣤⠶⠛⠁⠀              
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠉⠛⠛⠛⠲⠶⠶⠶⠤⠤⢤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⠤⠤⠶⠶⠶⠒⠛⠛⠛⠛⠛⠛⠓⠚⠚⠛⠛⠛⠋⠉⠁⠀⠀⠀⠀⠀

 """,
4: r"""
       0: {cabeça_nome}
       Is available: {cabeça_status}
       Attack: {cabeça_ataque}                              
       Defense: {cabeça_defesa}
       Energy consumption: {cabeça_energia_consumida}
               ^
               |                  |1: {arma_nome}
               |                  |Is available: {arma_status}
      ____     |    ____          |Attack: {arma_ataque}
     |oooo|  ____  |oooo| ------> |Defense: {arma_defesa}
     |oooo| '    ' |oooo|         |Energy consumption: {arma_energia_consumida}
     |oooo|/\_||_/\|oooo|          
     `----' / __ \  `----'           |2: {braço_esquerdo_nome}
    '/  |#|/\/__\/\|#|  \'           |Is available: {braço_esquerdo_status}
    /  \|#|| |/\| ||#|/  \           |Attack: {braço_esquerdo_ataque}
   / \_/|_|| |/\| ||_|\_/ \          |Defense: {braço_esquerdo_defesa}
  |_\/    O\=----=/O    \/_|         |Energy consumption: {braço_esquerdo_energia_consumida}
  <_>      |=\__/=|      <_> ------> |
  <_>      |------|      <_>         |3: {braço_direito_nome}
  | |   ___|======|___   | |         |Is available: {braço_direito_status}
 // \\ / |O|======|O| \  //\\        |Attack: {braço_direito_ataque}
 |  |  | |O+------+O| |  |  |        |Defense: {braço_direito_defesa}
 |\/|  \_+/        \+_/  |\/|        |Energy consumption: {braço_direito_energia_consumida}
 \__/  _|||        |||_  \__/        
       | ||        || |          |4: {perna_esquerda_nome}
      [==|]        [|==]         |Is available: {perna_esquerda_status}
      [===]        [===]         |Attack: {perna_esquerda_ataque}
       >_<          >_<          |Defense: {perna_esquerda_defesa}
      || ||        || ||         |Energy consumption: {perna_esquerda_energia_consumida}
      || ||        || || ------> |
      || ||        || ||         |5: {perna_direita_nome}
    __|\_/|__    __|\_/|__       |Is available: {perna_direita_status}
   /___n_n___\  /___n_n___\      |Attack: {perna_direita_ataque}
                                 |Defense: {perna_direita_defesa}
                                 |Energy consumption: {perna_direita_energia_consumida}
"""
}
play()